# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 23:07:41 2020/07/17 五
#     > Comment     :
# *****************************************************

open :
	vim ./common.c

