# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 22:16:22 2020/07/17 五
#     > Comment     :
# *****************************************************

make :
	g++ server.c ../common/common.c

open :
	vim server.c

run :
	./a.out 8888
