# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 22:14:51 2020/07/16 四
#     > Comment     :
# *****************************************************

make :

open :


